version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    image: pinyoclub/rest-backend:dev
    container_name: pc-rest-backend
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - VIRTUAL_HOST=pinyo-club-api.localhost
      - VIRTUAL_PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - vscode-extensions-pc-rest-backend:/root/.vscode-server/extensions
  db:
    image: mongo:6.0.4
    restart: always
    container_name: pc-db
    environment:
      MONGO_INITDB_DATABASE: pinyoclub
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/pc_mongo_user
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/pc_mongo_pw
    secrets:
      - pc_mongo_user
      - pc_mongo_pw
volumes:
  vscode-extensions-pc-rest-backend:
networks:
  proxy:
    external: true
    name: proxy_net
secrets:
  pc_mongo_user:
    file: ./mongodb/username
  pc_mongo_pw:
    file: ./mongodb/password

