version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    image: pinyoclub/rest-backend:dev
    container_name: pc-rest-backend
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - VIRTUAL_HOST=pinyo-club-api.localhost
      - VIRTUAL_PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - vscode-extensions-pc-rest-backend:/root/.vscode-server/extensions
volumes:
  vscode-extensions-pc-rest-backend:
networks:
  proxy:
    external: true
    name: proxy_net

